### ISSUE TITLE
Text input event behaviours (tracking issue)

### ISSUE THREAD

**Issue by felixangell** [felixangell/phi-editor#4]
Note that the behaviours aren't as simple; the bullet points provide simple summaries of the behaviour. There are a lot of edge cases, e.g. backspace has to join the lines to the last one if we backspace from the start of the line, etc.

This is not an exhaustive list.

These are the _default_ key bindings for the behaviours, though the system should allow for an easy rebinding with the configuration file:

* [x] left - move cursor left a letter
* [x] right - move cursor right a letter
* [x] delete - delete the letter in front
* [x] end - move to the end of the line
* [x] home - move to the start of the line
* [x] backspace - delete the last letter

---

* [x] alt+left - move left one word
* [x] alt+right - move right one word
* [x] alt+up - swap line up
* [x] alt+down - swap line down
* [ ] alt+home - go the start of the file
* [ ] alt+end - go to the end of the file
* [ ] alt+backspace - delete the last word

---

* [ ] ctrl+l - show/hide the command palette
* [x] ctrl+s - save
* [ ] ctrl+o - open command palette with the "open" command already entered
* [x] ctrl+w - close the current buffer

---

* [ ] ctrl+left - shift focus on the buffer to the left in the view
* [ ] ctrl+right - shift focus on the buffer to the right in the view
